name: "Workflow Dispatch"
on: push
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  call-lint:
    name: "Lint"
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  call-test:
    name: "Test"
    uses: ./.github/workflows/test.yml
    secrets: inherit
